{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "budget-buddy.fullname" . }}-postgresql
  labels:
    {{- include "budget-buddy.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.storage.storageClassName }}
  storageClassName: {{ .Values.postgresql.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
{{- end }}
