apiVersion: v1
kind: Secret
metadata:
  name: {{ include "budget-buddy.fullname" . }}-db
  labels:
    {{- include "budget-buddy.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
